# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubOfficial',
        ),
    ]
