# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifter',
            name='birth_date',
            field=models.DateTimeField(),
        ),
    ]
