# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20170917_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifter',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
