# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.6
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_DB=test_db


    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "Pipfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run:
          name: install dependencies
          command: sudo -u postgres psql -p 5433 -c "create user postgres with password ‘postgre314’;”
          command: sudo -u postgres psql -p 5433 -c "alter user postgres with superuser;"
          command: |
            sudo pip install pipenv
            export PIPENV_VENV_IN_PROJECT=1
            pipenv install

      - save_cache:
          paths:
            - ".venv/"
          key: v2-dependencies-{{ checksum "Pipfile.lock" }}

      # run tests!
      - run:
          name: run tests
          command: |
            source ~/repo/.venv/bin/activate
            # Perform tests here
            python athlitikos/manage.py test athlitikos/
            deactivate

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
