# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='activate_key',
        ),
        migrations.RemoveField(
            model_name='security',
            name='club_admin_key',
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
