# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PentathlonResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_put', models.DecimalField(decimal_places=3, max_digits=5)),
                ('shot_put_points', models.DecimalField(decimal_places=3, max_digits=5)),
                ('forty_meter', models.DecimalField(decimal_places=3, max_digits=5)),
                ('forty_meter_points', models.DecimalField(decimal_places=3, max_digits=5)),
                ('jump', models.DecimalField(decimal_places=3, max_digits=5)),
                ('jump_points', models.DecimalField(decimal_places=3, max_digits=5)),
                ('sum_all', models.DecimalField(decimal_places=3, max_digits=5)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Competition')),
                ('lifter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Lifter')),
            ],
        ),
    ]
