# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import resultregistration.enums


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='judge_level',
            field=models.CharField(choices=[('F', 'forbundsdommer'), ('Int. I', 'internasjonal_kategori_1'), ('Int. II', 'internasjonal_kategori_2'), ('K', 'kretsdommer')], default=resultregistration.enums.JudgeLevel('K'), max_length=10),
        ),
    ]
