# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifter',
            name='club',
        ),
        migrations.AddField(
            model_name='person',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Club'),
        ),
    ]
