# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifter',
            name='gender',
            field=models.CharField(choices=[('K', 'female'), ('M', 'male')], max_length=10, null=True, verbose_name='Kjønn'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateTimeField(verbose_name='Fødselsdato'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='Fornavn'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Etternavn'),
        ),
    ]
