# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='cheif_marshall',
            new_name='chief_marshall',
        ),
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=100, verbose_name='Navn'),
        ),
        migrations.AlterField(
            model_name='club',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Region'),
        ),
    ]
