# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='competition',
            field=models.ManyToManyField(blank=True, to='resultregistration.Competition'),
        ),
    ]
