# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0002_auto_20170920_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitionCategory', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('startDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupNumber', models.IntegerField()),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=300)),
                ('recordsDescription', models.CharField(max_length=300)),
                ('cheifMarshall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chiefMarshall', to='resultregistration.Staff')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Competition')),
                ('competitionLeader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitionLeader', to='resultregistration.Staff')),
                ('judges', models.ManyToManyField(related_name='judges', to='resultregistration.Judge')),
                ('jury', models.ManyToManyField(related_name='jury', to='resultregistration.Staff')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='resultregistration.Staff')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to='resultregistration.Staff')),
                ('technicalController', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicalController', to='resultregistration.Staff')),
                ('timeKeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeKeeper', to='resultregistration.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='MoveAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attemptNum', models.IntegerField()),
                ('moveType', models.IntegerField(choices=[(0, 'Snatch'), (1, 'Clean and jerk')])),
                ('weight', models.IntegerField()),
                ('success', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('resultID', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.IntegerField()),
                ('points', models.IntegerField()),
                ('points_veteran', models.IntegerField()),
                ('sinclair_coefficient', models.FloatField()),
                ('best_clean_and_jerk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_clean_and_jerk', to='resultregistration.MoveAttempt')),
                ('best_snatch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='best_snatch', to='resultregistration.MoveAttempt')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Group')),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Lifter')),
            ],
        ),
        migrations.AddField(
            model_name='moveattempt',
            name='parentResult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Result'),
        ),
        migrations.AlterUniqueTogether(
            name='moveattempt',
            unique_together=set([('parentResult', 'attemptNum')]),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set([('groupNumber', 'competition')]),
        ),
    ]
