# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 10:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resultregistration', '0002_auto_20171031_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
