# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0002_auto_20171013_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='age_group',
            field=models.CharField(choices=[('JM', 'junior_men'), ('JK', 'junior_women'), ('M1', 'master_men_35'), ('M2', 'master_men_40'), ('M3', 'master_men_45'), ('M4', 'master_men_50'), ('M5', 'master_men_55'), ('M6', 'master_men_60'), ('M7', 'master_men_65'), ('M8', 'master_men_70'), ('M9', 'master_men_75'), ('K1', 'master_women_35'), ('K2', 'master_women_40'), ('K3', 'master_women_45'), ('K4', 'master_women_50'), ('K5', 'master_women_55'), ('K6', 'master_women_60'), ('K7', 'master_women_65'), ('K8', 'master_women_70'), ('K9', 'master_women_75'), ('SM', 'senior_men'), ('SK', 'senior_women'), ('UM', 'youth_men'), ('UK', 'youth_women')], max_length=20, null=True, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='result',
            name='weight_class',
            field=models.CharField(max_length=10, null=True, verbose_name='Vektklasse'),
        ),
    ]
