# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0003_auto_20171017_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='competition',
        ),
        migrations.AddField(
            model_name='competition',
            name='host',
            field=models.CharField(default='GløsIL', max_length=100, verbose_name='Arrangør'),
            preserve_default=False,
        ),
    ]
