# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0003_auto_20170922_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='competitors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Lifter'),
        ),
    ]
