# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0003_auto_20171121_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldresults',
            old_name='points',
            new_name='points_with_sinclair',
        ),
    ]
