# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import resultregistration.enums


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0003_auto_20171016_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('Godkjent', 'approved'), ('Ikke godkjent', 'denied'), ('Ikke sendt', 'not_sent'), ('Til godkjenning', 'pending')], default=resultregistration.enums.Status('Ikke sendt'), max_length=30),
        ),
        migrations.AlterField(
            model_name='pendinggroup',
            name='approved',
            field=models.CharField(choices=[('Godkjent', 'approved'), ('Ikke godkjent', 'denied'), ('Ikke sendt', 'not_sent'), ('Til godkjenning', 'pending')], default=resultregistration.enums.Status('Ikke godkjent'), max_length=20, verbose_name='Status'),
        ),
    ]
