# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0004_auto_20171024_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competition_category',
            field=models.CharField(choices=[('Klubbstevne', 'cat1'), ('5-kamp', 'cat2'), ('NM', 'cat3')], max_length=100, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='group',
            name='competition_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_competition_leader', to='resultregistration.Judge', verbose_name='Stevneleder'),
        ),
        migrations.AlterField(
            model_name='group',
            name='time_keeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_time_keeper', to='resultregistration.Judge', verbose_name='Tidtaker'),
        ),
    ]
