# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0004_auto_20171017_1235'),
        ('resultregistration', '0003_auto_20171016_1301'),
    ]

    operations = [
    ]
