# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0004_auto_20171024_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_weight', models.FloatField(null=True, verbose_name='Kroppsvekt')),
                ('group', models.CharField(max_length=5, verbose_name='kategori')),
                ('snatch', models.IntegerField()),
                ('clean_and_jerk', models.IntegerField()),
                ('total', models.IntegerField()),
                ('lifter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Lifter')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='competition_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_competition_leader', to='resultregistration.Judge', verbose_name='Stevneleder'),
        ),
        migrations.AlterField(
            model_name='group',
            name='time_keeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_time_keeper', to='resultregistration.Judge', verbose_name='Tidtaker'),
        ),
    ]
