# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0004_auto_20171024_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_class', models.CharField(max_length=10, null=True, verbose_name='Vektklasse')),
                ('age_group', models.CharField(max_length=2, null=True, verbose_name='Kategori')),
                ('body_weight', models.FloatField(null=True, verbose_name='Kroppsvekt')),
                ('best_press', models.FloatField(blank=True, null=True, verbose_name='Press')),
                ('best_snatch', models.FloatField(blank=True, null=True, verbose_name='Rykk')),
                ('best_clean_and_jerk', models.FloatField(blank=True, null=True, verbose_name='Støt')),
                ('total_lift', models.FloatField(blank=True, null=True, verbose_name='Sammenlagt')),
                ('points', models.FloatField(blank=True, null=True, verbose_name='Poeng')),
                ('sinclair_coefficient', models.FloatField(blank=True, null=True, verbose_name='Koeffisient')),
            ],
        ),
        migrations.RemoveField(
            model_name='lifter',
            name='club',
        ),
        migrations.AddField(
            model_name='person',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Club'),
        ),
        migrations.AddField(
            model_name='result',
            name='lifter_club',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='host',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Arrangør'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateField(blank=True, help_text='år-måned-dag', null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='competition_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_competition_leader', to='resultregistration.Judge', verbose_name='Stevneleder'),
        ),
        migrations.AlterField(
            model_name='group',
            name='time_keeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_time_keeper', to='resultregistration.Judge', verbose_name='Tidtaker'),
        ),
        migrations.AddField(
            model_name='oldresults',
            name='competition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Competition'),
        ),
        migrations.AddField(
            model_name='oldresults',
            name='lifter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Person'),
        ),
        migrations.AddField(
            model_name='oldresults',
            name='lifter_club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Club'),
        ),
    ]
