# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0004_group_competitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Group'),
        ),
    ]
