# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0004_auto_20171104_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='cheif_marshall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_chief_marshall', to='resultregistration.Judge', verbose_name='Chief Marshall'),
        ),
        migrations.AlterField(
            model_name='group',
            name='competition_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_competition_leader', to='resultregistration.Judge', verbose_name='Stevneleder'),
        ),
        migrations.AlterField(
            model_name='group',
            name='competitors',
            field=models.ManyToManyField(blank=True, null=True, to='resultregistration.Lifter'),
        ),
        migrations.AlterField(
            model_name='group',
            name='judges',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups_judges', to='resultregistration.Judge'),
        ),
        migrations.AlterField(
            model_name='group',
            name='jury',
            field=models.ManyToManyField(blank=True, default='', null=True, related_name='groups_juries', to='resultregistration.Judge', verbose_name='Jurie'),
        ),
        migrations.AlterField(
            model_name='group',
            name='secretary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sekretær'),
        ),
        migrations.AlterField(
            model_name='group',
            name='speaker',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Taler'),
        ),
        migrations.AlterField(
            model_name='group',
            name='technical_controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_technical_controller', to='resultregistration.Judge', verbose_name='Teknisk kontrollør'),
        ),
        migrations.AlterField(
            model_name='group',
            name='time_keeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_time_keeper', to='resultregistration.Judge', verbose_name='Tidtaker'),
        ),
        migrations.AlterField(
            model_name='moveattempt',
            name='success',
            field=models.BooleanField(max_length=100),
        ),
    ]
