# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0005_auto_20171104_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='competitors',
            field=models.ManyToManyField(blank=True, to='resultregistration.Lifter'),
        ),
        migrations.AlterField(
            model_name='group',
            name='judges',
            field=models.ManyToManyField(blank=True, related_name='groups_judges', to='resultregistration.Judge'),
        ),
        migrations.AlterField(
            model_name='group',
            name='jury',
            field=models.ManyToManyField(blank=True, default='', related_name='groups_juries', to='resultregistration.Judge', verbose_name='Jurie'),
        ),
    ]
