# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0005_auto_20170922_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(verbose_name='Fødselsdato'),
        ),
    ]
