# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0005_auto_20171104_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldresults',
            name='age_group',
            field=models.CharField(max_length=5, null=True, verbose_name='Kategori'),
        ),
    ]
