# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0005_auto_20171024_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalLifter',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resultregistration.Person')),
                ('birth_date', models.DateField(null=True, verbose_name='Fødselsdato')),
                ('gender', models.CharField(choices=[('K', 'female'), ('M', 'male')], max_length=10, null=True, verbose_name='Kjønn')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
            ],
            bases=('resultregistration.person',),
        ),
        migrations.AlterField(
            model_name='internationalresult',
            name='lifter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.InternationalLifter'),
        ),
    ]
