# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0006_auto_20171024_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationallifter',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Land'),
        ),
    ]
