# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0006_auto_20170922_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='points',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
