# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0006_auto_20171104_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveattempt',
            name='success',
            field=models.BooleanField(),
        ),
    ]
