# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0007_auto_20170922_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='points_veteran',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='sinclair_coefficient',
            field=models.FloatField(null=True),
        ),
    ]
