# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import resultregistration.enums


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0007_auto_20171024_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Godkjent', 'approved'), ('Ikke godkjent', 'denied'), ('Ikke sendt', 'not_sent'), ('Til godkjenning', 'pending')], default=resultregistration.enums.Status('Ikke sendt'), max_length=30)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Competition')),
                ('competitors', models.ManyToManyField(to='resultregistration.Lifter')),
            ],
        ),
        migrations.RemoveField(
            model_name='internationallifter',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='internationalresult',
            name='clean_and_jerk',
        ),
        migrations.RemoveField(
            model_name='internationalresult',
            name='snatch',
        ),
        migrations.RemoveField(
            model_name='internationalresult',
            name='total',
        ),
        migrations.AddField(
            model_name='internationalresult',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='internationalresult',
            name='age_group',
            field=models.CharField(choices=[('JM', 'junior_men'), ('JK', 'junior_women'), ('M1', 'master_men_35'), ('M2', 'master_men_40'), ('M3', 'master_men_45'), ('M4', 'master_men_50'), ('M5', 'master_men_55'), ('M6', 'master_men_60'), ('M7', 'master_men_65'), ('M8', 'master_men_70'), ('M9', 'master_men_75'), ('K1', 'master_women_35'), ('K2', 'master_women_40'), ('K3', 'master_women_45'), ('K4', 'master_women_50'), ('K5', 'master_women_55'), ('K6', 'master_women_60'), ('K7', 'master_women_65'), ('K8', 'master_women_70'), ('K9', 'master_women_75'), ('SM', 'senior_men'), ('SK', 'senior_women'), ('UM', 'youth_men'), ('UK', 'youth_women')], max_length=20, null=True, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='internationalresult',
            name='best_clean_and_jerk',
            field=models.ForeignKey(blank=True, db_column='best_clean_and_jerk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='international_best_clean', to='resultregistration.MoveAttempt'),
        ),
        migrations.AddField(
            model_name='internationalresult',
            name='best_snatch',
            field=models.ForeignKey(blank=True, db_column='best_snatch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='international_best_snatch', to='resultregistration.MoveAttempt'),
        ),
        migrations.AddField(
            model_name='internationalresult',
            name='points_with_sinclair',
            field=models.FloatField(blank=True, null=True, verbose_name='Poeng med sinclair'),
        ),
        migrations.AddField(
            model_name='internationalresult',
            name='points_with_veteran',
            field=models.FloatField(blank=True, null=True, verbose_name='Veteranpoeng'),
        ),
        migrations.AddField(
            model_name='internationalresult',
            name='sinclair_coefficient',
            field=models.FloatField(blank=True, db_column='sinclair_coefficient', null=True),
        ),
        migrations.AddField(
            model_name='internationalresult',
            name='total_lift',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total poeng'),
        ),
        migrations.AddField(
            model_name='internationalresult',
            name='veteran_coefficient',
            field=models.FloatField(blank=True, db_column='melzer_faber_coefficient', null=True),
        ),
        migrations.AddField(
            model_name='internationalresult',
            name='weight_class',
            field=models.CharField(max_length=10, null=True, verbose_name='Vektklasse'),
        ),
        migrations.AlterField(
            model_name='internationalresult',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.InternationalGroup'),
        ),
        migrations.AlterField(
            model_name='internationalresult',
            name='lifter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Lifter'),
        ),
        migrations.DeleteModel(
            name='InternationalLifter',
        ),
    ]
