# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0007_auto_20171104_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldPentathlonResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.CharField(blank=True, max_length=20, null=True)),
                ('shot_put', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('shot_put_points', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('forty_meter', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('forty_meter_points', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('jump', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('jump_points', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('sum_all', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Competition')),
                ('lifter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Person')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.OldResults')),
            ],
        ),
    ]
