# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0007_auto_20171019_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='competition_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Judge', verbose_name='Stevneleder'),
        ),
        migrations.AlterField(
            model_name='group',
            name='judges',
            field=models.ManyToManyField(related_name='judges', to='resultregistration.Judge'),
        ),
        migrations.AlterField(
            model_name='group',
            name='jury',
            field=models.ManyToManyField(default='', related_name='groups_juries', to='resultregistration.Judge', verbose_name='Jurie'),
        ),
        migrations.AlterField(
            model_name='pendinggroup',
            name='competition_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_competitionleader', to='resultregistration.Judge', verbose_name='Stevneleder'),
        ),
        migrations.RemoveField(
            model_name='pendinggroup',
            name='jury',
        ),
        migrations.AddField(
            model_name='pendinggroup',
            name='jury',
            field=models.ManyToManyField(default='', related_name='pending_juries', to='resultregistration.Judge', verbose_name='Jurie'),
        ),
    ]
