# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import resultregistration.validators


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0008_auto_20170922_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competitionCategory',
            field=models.CharField(max_length=100, validators=[resultregistration.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='competition',
            name='startDate',
            field=models.DateField(help_text='år-måned-dag'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=40, validators=[resultregistration.validators.validate_name], verbose_name='Fornavn'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=100, validators=[resultregistration.validators.validate_name], verbose_name='Etternavn'),
        ),
    ]
