# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import resultregistration.validators


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0008_auto_20170922_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubName', models.CharField(max_length=100, validators=[resultregistration.validators.validate_name])),
                ('region', models.CharField(max_length=100, validators=[resultregistration.validators.validate_name])),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='competition',
            name='competitionCategory',
            field=models.CharField(max_length=100, validators=[resultregistration.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='competition',
            name='startDate',
            field=models.DateField(help_text='år-måned-dag'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=40, validators=[resultregistration.validators.validate_name], verbose_name='Fornavn'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=100, validators=[resultregistration.validators.validate_name], verbose_name='Etternavn'),
        ),
        migrations.AddField(
            model_name='lifter',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Club'),
        ),
    ]
