# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0008_auto_20171025_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalresult',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.InternationalGroup', verbose_name='Pulje'),
        ),
        migrations.AlterField(
            model_name='internationalresult',
            name='lifter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultregistration.Lifter', verbose_name='Utøver'),
        ),
    ]
