# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0009_auto_20170929_0625'),
        ('resultregistration', '0009_auto_20170926_1332'),
    ]

    operations = [
    ]
