# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0010_merge_20170929_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='best_clean_and_jerk',
        ),
        migrations.RemoveField(
            model_name='result',
            name='best_snatch',
        ),
        migrations.AlterField(
            model_name='club',
            name='clubName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='club',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
