# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultregistration', '0012_merge_20171006_1117'),
        ('resultregistration', '0012_auto_20171009_1058'),
    ]

    operations = [
    ]
